"""All the constants of this library."""

from aalec.constants.beeper import (
    DUTY50,
    t_a_1,
    t_a_2,
    t_c_1,
    t_c_2,
    t_d_1,
    t_e_1,
    t_f_1,
    t_g_1,
    t_h_1,
    t_off,
)
from aalec.constants.button import PRESSED, RELEASED, SAMPLE_PERIOD
from aalec.constants.display import (
    BLACK,
    DISPLAY_HEIGHT,
    DISPLAY_WIDTH,
    LINE_HEIGHT,
    MAX_LINE_COUNT,
    WHITE,
)
from aalec.constants.general import (
    PIN_ADC,
    PIN_BEEPER,
    PIN_BUTTON,
    PIN_ENCODER_TRACK_1,
    PIN_ENCODER_TRACK_2,
    PIN_RGB_STRIP,
    PIN_RX,
    PIN_SCL,
    PIN_SDA,
    PIN_TX,
)

__all__ = [
    "BLACK",
    "DISPLAY_HEIGHT",
    "DISPLAY_WIDTH",
    "DUTY50",
    "LINE_HEIGHT",
    "MAX_LINE_COUNT",
    "PIN_ADC",
    "PIN_BEEPER",
    "PIN_BUTTON",
    "PIN_ENCODER_TRACK_1",
    "PIN_ENCODER_TRACK_2",
    "PIN_RGB_STRIP",
    "PIN_RX",
    "PIN_SCL",
    "PIN_SDA",
    "PIN_TX",
    "PRESSED",
    "RELEASED",
    "SAMPLE_PERIOD",
    "t_a_1",
    "t_a_2",
    "t_c_1",
    "t_c_2",
    "t_d_1",
    "t_e_1",
    "t_f_1",
    "t_g_1",
    "t_h_1",
    "t_off",
    "WHITE",
]
